#define AND 1
#define ARRAY 2
#define ATRIB 3
#define BIGGER_THAN 4
#define BOOLEAN 5
#define CHAR 6
#define CLOSED_CURLY_BRACKET 7
#define CLOSED_RIGHT_BRACKET 8
#define CLOSED_ROUND_BRACKET 9
#define COMMA 10
#define CONSTANT 11
#define DIV 12
#define ELSE 13
#define EQUALS 14
#define FOR 15
#define GREATER_OR_EQUAL 16
#define IDENTIFIER 17
#define IF 18
#define INTEGER 19
#define MINUS 20
#define MOD 21
#define MUL 22
#define OF 23
#define OPEN_CURLY_BRACKET 24
#define OPEN_RIGHT_BRACKET 25
#define OPEN_ROUND_BRACKET 26
#define OR 27
#define PLUS 28
#define PRINT 29
#define READ 30
#define SEMI_COLON 31
#define SMALLER_OR_EQUAL 32
#define SMALLER_THAN 33
#define WHILE 34